# Generated by Django 4.1 on 2022-08-25 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stdcat', models.CharField(choices=[('国标', 'GB/T'), ('行标', 'QC/T')], max_length=30)),
                ('stdnum', models.IntegerField(max_length=10)),
                ('stdyear', models.DateField()),
                ('stdname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Standard_to_Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.author')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.standard')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='post',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='board',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='starter',
        ),
        migrations.DeleteModel(
            name='Board',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.AddField(
            model_name='standard',
            name='authors',
            field=models.ManyToManyField(through='boards.Standard_to_Author', to='boards.author'),
        ),
    ]
