# Generated by Django 4.1 on 2022-08-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_author_standard_standard_to_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='stdnum',
            field=models.IntegerField(),
        ),
    ]
