# Generated by Django 4.1 on 2022-08-26 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_alter_standard_stdnum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Standard_to_Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.company')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.standard')),
            ],
        ),
        migrations.AddField(
            model_name='standard',
            name='companies',
            field=models.ManyToManyField(through='boards.Standard_to_Company', to='boards.company'),
        ),
    ]
